### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by paurosello** [saguas/jasper_erpnext_report#11]
Hello @saguas, thank you very much for your work!

I am having some localisation issues with Jasper installed in local mode and using Spanish characters like "opción" where it is represented "opci&#211;n" in the final PDF.

Do you think there is any way to fix this from your side or should I test with the server mode?

Thank you very much!

**Comment by saguas** [comment]
Sorry i don't see your post. I thinks the problems is yours. I can write "opção" in portuguese.
Did you install all the microsoft TrueType fonts (See How to Install in Readme.md)
